import { setup, as, admin } from './harness.mjs';
const db = await setup();
const A='11111111-1111-4111-8111-111111111111', B='22222222-2222-4222-8222-222222222222';
await admin(db, `insert into auth.users values ('${A}','a@x'),('${B}','b@x');
 insert into public.profiles (id,username,display_name,avatar_color_seed) values ('${A}','alice','A','a'),('${B}','bob','B','b');`);
let pass=0, fail=0; const check=(name,cond,detail)=>{cond?pass++:fail++; console.log((cond?'PASS':'FAIL')+'  '+name+(cond?'':'  '+JSON.stringify(detail)));};
const R='33333333-3333-4333-8333-333333333333';
const ins=(uid,id,owner)=>as(db,'authenticated',uid,`insert into public.recipes (id,owner_id,name,base_spirit,method,difficulty,prep_time_minutes,ingredients,steps) values ($1,$2,'X','gin','shake','easy',5,'[{"i":1}]','{s}')`,[id,owner]);
let r=await ins(A,R,A); check('A publishes own recipe (uuid id)', r.ok, r);
r=await ins(B,'44444444-4444-4444-8444-444444444444',A); check('B cannot publish as A (forged owner)', !r.ok && r.code==='42501', r);
r=await as(db,'authenticated',B,`update public.recipes set name='hacked' where id=$1`,[R]); check('B cannot update A recipe (0 rows)', r.ok && r.affected===0, r);
r=await as(db,'authenticated',B,`delete from public.recipes where id=$1`,[R]); check('B cannot delete A recipe (0 rows)', r.ok && r.affected===0, r);
r=await as(db,'authenticated',B,`insert into public.recipes (id,owner_id,name,base_spirit,method,difficulty,prep_time_minutes,ingredients,steps) values ($1,$2,'X','gin','shake','easy',5,'[{"i":1}]','{s}') on conflict (id) do update set name='hijack'`,[R,B]); check('B cannot hijack A recipe via upsert', !r.ok, r);
r=await as(db,'anon',null,`select count(*)::int c from public.recipes`); check('anon can read published recipes', r.ok && r.rows[0].c===1, r);
r=await as(db,'authenticated',B,`insert into public.likes (user_id,recipe_id) values ($1,$2)`,[B,R]); check('B likes A recipe', r.ok, r);
r=await as(db,'authenticated',B,`insert into public.likes (user_id,recipe_id) values ($1,$2)`,[B,R]); check('duplicate like rejected', !r.ok && r.code==='23505', r);
r=await as(db,'authenticated',B,`insert into public.likes (user_id,recipe_id) values ($1,$2)`,[A,R]); check('forged like identity rejected', !r.ok && r.code==='42501', r);
r=await as(db,'authenticated',A,`insert into public.follows (follower_id,following_id) values ($1,$1)`,[A]); check('self-follow rejected', !r.ok, r);
r=await as(db,'authenticated',A,`insert into public.blocks (blocker_id,blocked_id) values ($1,$2)`,[A,B]); check('A blocks B', r.ok, r);
await admin(db,`delete from public.likes`);
r=await as(db,'authenticated',B,`insert into public.likes (user_id,recipe_id) values ($1,$2)`,[B,R]); check('blocked B cannot like A recipe (SECURITY DEFINER helper sees block)', !r.ok && r.code==='42501', r);
r=await as(db,'authenticated',B,`insert into public.follows (follower_id,following_id) values ($1,$2)`,[B,A]); check('blocked B cannot follow A', !r.ok && r.code==='42501', r);
r=await as(db,'authenticated',B,`select count(*)::int c from public.blocks`); check('B cannot read A block list', r.ok && r.rows[0].c===0, r);
r=await as(db,'authenticated',A,`insert into public.subscribers (user_id,is_premium) values ($1,true)`,[A]); check('premium self-grant rejected', !r.ok, r);
r=await as(db,'authenticated',A,`insert into public.reports (reporter_id,target_type,target_id,reason) values ($1,'user',$2,'spam')`,[A,B]); check('report filed', r.ok, r);
r=await as(db,'authenticated',A,`insert into public.reports (reporter_id,target_type,target_id,reason) values ($1,'user',$2,'spam')`,[A,B]); check('duplicate open report rejected', !r.ok && r.code==='23505', r);
r=await as(db,'authenticated',B,`select count(*)::int c from public.reports`); check('B cannot read A reports', r.ok && r.rows[0].c===0, r);
r=await as(db,'authenticated',A,`insert into storage.objects (bucket_id,name) values ('recipe-media',$1)`,[`${A}/${R}/photo`]); check('A uploads under own prefix', r.ok, r);
r=await as(db,'authenticated',B,`insert into storage.objects (bucket_id,name) values ('recipe-media',$1)`,[`${A}/${R}/photo2`]); check('B cannot upload under A prefix', !r.ok, r);
r=await as(db,'authenticated',B,`delete from storage.objects where name=$1`,[`${A}/${R}/photo`]); check('B cannot delete A media (0 rows)', r.ok && r.affected===0, r);
// first-sign-in profile creation semantics used by the new client code
const C='55555555-5555-4555-8555-555555555555'; await admin(db,`insert into auth.users values ('${C}','c@x')`);
r=await as(db,'anon',null,`insert into public.profiles (id,username,display_name,avatar_color_seed) values ($1,'carol','C','c')`,[C]); check('anon (pending confirmation) cannot create profile', !r.ok && r.code==='42501', r);
r=await as(db,'authenticated',C,`insert into public.profiles (id,username,display_name,avatar_color_seed) values ($1,'alice','C','c') on conflict (id) do nothing`,[C]); check('first sign-in: taken username -> 23505 (client retries with suffix)', !r.ok && r.code==='23505', r);
r=await as(db,'authenticated',C,`insert into public.profiles (id,username,display_name,avatar_color_seed) values ($1,'carol','C','c') on conflict (id) do nothing returning id`,[C]); check('first sign-in: profile created', r.ok && r.rows.length===1, r);
r=await as(db,'authenticated',C,`insert into public.profiles (id,username,display_name,avatar_color_seed) values ($1,'carol2','OVERWRITE','c') on conflict (id) do nothing returning id`,[C]); check('repeat first-sign-in never overwrites an existing profile', r.ok && r.rows.length===0, r);
await admin(db,`delete from auth.users where id='${B}'`);
r=await as(db,'authenticated',A,`select count(*)::int c from public.reports where reporter_id=$1`,[A]); check('reports survive reported-user deletion', r.ok && r.rows[0].c===1, r);
await admin(db,`delete from auth.users where id='${A}'`);
r=await admin(db,`select count(*)::int c from public.reports where reporter_id is null`); 
const rr = await db.query(`select count(*)::int c from public.reports where reporter_id is null`); check('reporter deletion -> reporter_id SET NULL', rr.rows[0].c===1, rr.rows);
const rc = await db.query(`select count(*)::int c from public.recipes`); check('owner deletion cascades recipes', rc.rows[0].c===0, rc.rows);
// --- production hardening migration (20260926120000) ---
const D='66666666-6666-4666-8666-666666666666';
await admin(db,`insert into auth.users values ('${D}','d@x'); insert into public.profiles (id,username,display_name,avatar_color_seed) values ('${D}','dave','D','d')`);
const R2='77777777-7777-4777-8777-777777777777';
r=await as(db,'authenticated',D,`insert into public.recipes (id,owner_id,name,base_spirit,method,difficulty,prep_time_minutes,ingredients,steps,created_at) values ($1,$2,'X','gin','shake','easy',5,'[{"i":1}]','{s}','2099-01-01') returning created_at`,[R2,D]);
check('client-supplied future created_at is ignored', r.ok && new Date(r.rows[0].created_at).getFullYear() < 2099, r);
r=await as(db,'authenticated',D,`insert into public.recipes (id,owner_id,name,base_spirit,method,difficulty,prep_time_minutes,ingredients,steps) values ($1,$2,'Y','gin','shake','easy',5,'[{"i":1}]','{s}') on conflict (id) do update set name=excluded.name, created_at='2099-01-01' returning created_at, name`,[R2,D]);
check('upsert keeps original created_at', r.ok && r.rows[0].name==='Y' && new Date(r.rows[0].created_at).getFullYear() < 2099, r);
const C2='55555555-5555-4555-8555-555555555555';
r=await as(db,'authenticated',D,`update public.recipes set owner_id=$1 where id=$2 returning owner_id`,[C2,R2]);
check('owner_id cannot be changed by its owner', (!r.ok) || (r.rows[0]?.owner_id===D), r);
r=await as(db,'authenticated',D,`update public.recipes set photo_url='file:///var/x.jpg' where id=$1`,[R2]);
check('non-https photo_url rejected', !r.ok && r.code==='23514', r);
r=await as(db,'authenticated',D,`update public.profiles set bio=repeat('x',301) where id=$1`,[D]);
check('over-long bio rejected', !r.ok && r.code==='23514', r);
r=await as(db,'authenticated',D,`insert into public.reports (reporter_id,target_type,target_id,reason) values ($1,'recipe',$2,'made-up')`,[D,R2]);
check('unknown report reason rejected', !r.ok && r.code==='23514', r);
await as(db,'authenticated',C2,`insert into public.likes (user_id,recipe_id) values ($1,$2)`,[C2,R2]);
r=await as(db,'anon',null,`select * from public.recipe_like_counts($1)`,[[R2]]);
check('recipe_like_counts aggregates for anon', r.ok && r.rows.length===1 && Number(r.rows[0].like_count)===1, r);
r=await as(db,'authenticated',D,`insert into public.subscribers (user_id,is_premium,last_event_at) values ($1,true,now())`,[D]);
check('premium self-grant still rejected after hardening', !r.ok, r);

console.log(`\n${pass} passed, ${fail} failed`);
